baseURL = ''
languageCode = 'pt-BR'
title = 'Matheus Laidler Page'
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

		
[params]
  author = "Acervo de TI"
  description = "Projeto que auxilia no aprendizado de conteúdos via divulgação científica, com materiais sobre o mundo da tecnologia e hacking."
  avatar = "../../images/perfil.jpg" #foi feito ../../ para funcionar em abas de tags e categorias específicas - n achei a parte do codigo epecifico dessas paginas pra arrumar por la q nem fiz com os outros
  github = "matheuslaidler"
  medium = "matheuslaidler"
  gitbook = "matheuslaidler"
  #stackoverflow = "23312896"
  instagram = "matheuslaidler"
  youtube = "@matheuslaidler" #/channel/UCkFbbZX6TG6eZPugmW32YFA/
  gitlab = "matheuslaidler"
  linkedin = "laidlervidal"
  facebook = "matheus.laidler"
  twitter = "matheuslaidler"
  email = "matheuslaidler@protonmail.com"
  url = "https://gitlab.com/matheuslaidler" #se não colocar ficará como o link do site raiz
  keywords = "matheus laidler, matheuslaidler, matheus-laidler, mlaidler, cibersegurança, wayofsecurity, wayofsec, road2tech, road2technology, acervo de TI, artigos, write ups, blog"
  rss = false
  lastmod = true
  favicon = "images/terminal.png"
  location = "Brazil"
  userStatusEmoji = ">_"	#💲 👽 🇲🇱 😀		💻(laptop)	🤖(robo)	👨‍💻(tecnologo)	🖱️(mouse)	🖥️(monitor)	🌐(globo meridianos)	📁(pastas)	📃(pagina)	🤓(nerd)	💀(caveira)	😊(sorriso2)	❤️(coração)	🏡(home)	🎖️(medalha)	😎 (oculos)	👻(fantasma)	👽(alien)	😜	🙃	🤨	😌	😁 	🎃	🤙	👋	✍️	🧠	👁	👀	👌	🧑	🕵️‍♂️	👨‍🏫	👤	🤵🏻	🕵🏻‍♂️	❄️	🌎	🔥	⌨️	💎	🔬	🇲🇱 🧠
  enableGitalk = true
    
  [params.gitalk]
    clientID = "097939594343c0ecdfda" # Your client ID : 097939594343c0ecdfda
    clientSecret = "cd61ebe34d6edd02560e48a54e4dc397c5b9fade" # Your client secret : cd61ebe34d6edd02560e48a54e4dc397c5b9fade
    repo = "repo" # matheuslaidler.github.io - # 您的博客的github地址Repository name，例如：xxxx.github.io
    owner = "matheuslaidler" #  您的GitHub ID
    admin = "matheuslaidler" #  您的GitHub ID
    id = "location.pathname" #  文章页面的链接地址就是ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # 设置为true，如果是管理员登录，会自动创建issue，如果是false，需要管理员手动添加第一个评论(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # 可以自行添加反向代理

	
  #[[params.links]] 
    #title = "Rascunhos"
    #href = "https://matheuslaidler.gitbook.io"
	#icon = "images/gitbook.png" #sem nada => icone padrão de link => "/images/link.png"
	


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
